project_id = "kvvqkzwrkselznrnqcbi"

[functions]
enabled = true

[functions.check-trial-expiry]
verify_jwt = false

[functions.send-trial-reminders]
verify_jwt = false

[functions.send-trial-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true